-- Admin overview + host-rejoin support
--
-- 1. admin_config — single-row table with a secret admin token. The token
--    is autogenerated on first run; the project owner reads it from the
--    Supabase SQL editor (or rotates it manually) and pastes it into
--    /admin in the app. RLS is on with no anon policies, so the table is
--    invisible outside of the RPCs below.
--
-- 2. _is_admin(token) — single-row check used by every admin RPC. Stays
--    SECURITY DEFINER so the RPCs themselves can run as anon while the
--    auth check still has access to admin_config.
--
-- 3. admin_list_rooms(token) — returns every room with uploader/photo
--    counts, expiry, host_token. host_token is included so admin can
--    rescue lost-host scenarios without rotating the room.
--
-- 4. admin_delete_room(token, room_id) — deletes the room (cascades take
--    care of uploaders/photos/players/guesses) and also removes the
--    matching storage objects under {room_id}/*. The DELETE from
--    storage.objects fires Supabase's internal hook that removes the
--    underlying files.
--
-- 5. verify_host_token(code, host_token) — boolean check used by the
--    "I'm a returning host" form so the client can confirm the token
--    matches before stashing it locally.

-- ---------- admin_config -----------------------------------------------------

create table public.admin_config (
  id          int primary key default 1,
  admin_token text not null,
  created_at  timestamptz not null default now(),
  check (id = 1)
);

alter table public.admin_config enable row level security;
-- No anon policies. The RPCs below are the only access path.

insert into public.admin_config (id, admin_token)
values (1, public._generate_token())
on conflict (id) do nothing;

-- ---------- _is_admin -------------------------------------------------------

create or replace function public._is_admin(p_token text)
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.admin_config where admin_token = p_token
  );
$$;

-- ---------- admin_list_rooms ------------------------------------------------

create or replace function public.admin_list_rooms(p_admin_token text)
returns table (
  id                uuid,
  code              text,
  state             text,
  photos_per_player int,
  host_message      text,
  uploader_count    bigint,
  photo_count       bigint,
  created_at        timestamptz,
  expires_at        timestamptz,
  host_token        text
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public._is_admin(p_admin_token) then
    raise exception 'unauthorized';
  end if;

  return query
    select
      r.id,
      r.code,
      r.state,
      r.photos_per_player,
      r.host_message,
      (select count(*) from public.uploaders u where u.room_id = r.id),
      (select count(*) from public.photos p where p.room_id = r.id),
      r.created_at,
      r.expires_at,
      r.host_token
    from public.rooms r
    order by r.created_at desc;
end;
$$;

revoke all on function public.admin_list_rooms(text) from public;
grant execute on function public.admin_list_rooms(text) to anon;

-- ---------- admin_delete_room -----------------------------------------------

create or replace function public.admin_delete_room(
  p_admin_token text,
  p_room_id     uuid
) returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public._is_admin(p_admin_token) then
    raise exception 'unauthorized';
  end if;

  -- Remove storage objects first; Supabase's storage hook cleans up the
  -- underlying files when rows are deleted from storage.objects.
  delete from storage.objects
    where bucket_id = 'room-photos'
      and name like (p_room_id::text || '/%');

  -- Cascades to uploaders, photos, players, guesses
  delete from public.rooms where id = p_room_id;
end;
$$;

revoke all on function public.admin_delete_room(text, uuid) from public;
grant execute on function public.admin_delete_room(text, uuid) to anon;

-- ---------- verify_host_token -----------------------------------------------

create or replace function public.verify_host_token(
  p_room_code  text,
  p_host_token text
) returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.rooms
    where code = p_room_code
      and host_token = p_host_token
  );
$$;

revoke all on function public.verify_host_token(text, text) from public;
grant execute on function public.verify_host_token(text, text) to anon;
